environment:

  matrix:
    - TOXENV: py38-test

install:
  - C:\Miniconda3-x64\\Scripts\\activate"
  - conda.exe install -c conda-forge -y tox

build: off

test_script:
  - python.exe -m tox -c .appveyor-tox-debug.ini -vv -e run-cmd -- python.exe -c "import qutip; print(qutip.__version__)"
    #- "python.exe -m tox -c .appveyor-tox.ini -vv -e %TOXENV%"
