environment:

  matrix:
    - PYTHON: C:\\Miniconda3-x64\\envs\\qalgebra_testenv\\python.exe
      PATH: C:\Miniconda3-x64\envs\qalgebra_testenv\Scripts;%PATH%
      PYTHONIOENCODING: utf-8

install:
  - chcp 65001
  - C:\\Miniconda3-x64\\Scripts\\activate
  - conda.exe update -n base -c defaults -y conda
  - conda.exe create -n qalgebra_testenv -y python=3.8
  - "%PYTHON% --version"
  - "%PYTHON% -m pip install cython numpy scipy tox"
  - "%PYTHON% -m pip install qutip"
  - "%PYTHON% -m pip install -e .[dev]"

build: off

test_script:
  - "%PYTHON% -m pytest -vvv --doctest-modules --cov=qalgebra --nbval --sanitize-with docs\nbval_sanitize.cfg --durations=10 -x -s src tests docs README.rst"
