# Config file for automatic testing at travis-ci.org
dist: xenial
language: python
env:
  global:
    - COVERALLS_PARALLEL=true
matrix:
  fast_finish: true
  include:
    - name: Check code style
      python: 3.8
      env: TOXENV="run-blackcheck,run-isortcheck"
    - name: Docs
      python: 3.8
      env:
        - DOCS="true"
        - secure: "FfWOPCxwhF7H6UFqdOAiO7OIoeAVjHQpTTvQ84QxZpH4TC0zLPUMfhB1H5yKJdWfxb0L9RKRH6XYVF5G2UQEnVUkyW2dkZ/KFZbndtIH2ytA3WDGQ+D24LCkVuYiiBsJj8NyWUwvnHyumSlGgTi7BbA+unIkEWLBA2/0SkvLsSTHh80b96dmkOn/7hbaVI+q3IHv3Y/Mu12pIXNGlsesa6nJmtfhgzSKopwjHlCE6XWVq+BRC6pYTlgLPImuE6Tss+v3tJf6Ipv+CL2LgghFcn1vggZAS34yld66s4TKO1RD5UiYuvnTrDxIHJJC64TFGiBZP3wQNfSMLDx8MzN8jw6wxkA+gFCxxcASGyG8eKPQJkfNczODS0CVLThpoAUxIwljmO9hmfa+BUV9+4oXPdIBGAsuriEOLhOI9iRgBfH3ou44z1cos8kdn9duKZiI2Sitk4XfpdN/O9DDev5s8JJraxGpJh3zIZLRcwnHl4va5wMG45Sw0ivJaeufc7wb0ac3JlPAEvChrMnidUmdD2iy24WHaNlmf8d5aHQ3YKootI3hbi3ju0VmMug5SDiKEnuFTaVvj1aToSIEBWOU7Vz7dwb3ZDim97hcfWLTVhlVGopCu8JFRhuKSMti3EAlcuucV/2FZPLN42G01VXiH4OVe9/98AupxsgQoKfb9ps="
        - BINTRAY_USER=goerz
        - BINTRAY_SUBJECT=qalgebra
        - BINTRAY_REPO=qalgebra
        - BINTRAY_PACKAGE=qalgebra
        - secure: WdN0tTvb6g0wvRhPLj06SEd1CWQYB5O6ZXpahABz9QqZSSRKUkBa/hR8qqWb+DBt9DZwBelEH30mGJcnIy5+JyGtpdq/vRsyZ+0XweCVMe5SlynEj15ZMUCS3p8Vf3qxWElNM3w1q6Pg7wBimthfF/DJxr0fF0DKNllG/7AOQ/zikV39QBWHAuBwchpjALJC32UJXYVg1kpKnWBZike1zwsb12Gd88uIFDj8yQGF6hlelwR1/LrI85XaSd4b5Yq4s4fsTjhIOQgEBsfljef5C2jwwD5nWhmWjnDASFlxZDSnEerjwvWIVLI+0qcBb0JDq4GnxB9p+IDZtJdmL5xa8xOiLGuiNrzScdX3r/G+OGopjeOXKaoVQyDdpWVyVS/rmYccPdvrLT871f+Z8I/7mgwrS13OgQWB7Ka7oFTfhmhdDRbv9I8zV3gKK7z2DOT5P888xfggfPYjeqPzd9x9PzcfInenHiPpVKUlN9/15/t3JQQ8wGS/z/+00tc0CsuFKTHwoWsxo8aLr99vimShsGpsuRrJBVNMeqkB8mFCPjrA5kuPJNwEu8OtK/nr3ak35zjB43DPnYuGI9Lmq5Vd1Kivch5IXrK7fCOJ1pa3mZhugyjPAUws/AMahgPA3CRDinnFHzZYRQLdBZdfRPQZhEIGGo1Yp+RJPo1XpC1dEuQ=
      addons:
        apt_packages:
          - pandoc
    - name: Python 3.8
      python: 3.8
      env: TOXENV=py38-test

install:
  # any failure stops the build
  - set -e
  - export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
  - travis_wait source .travis/texlive/texlive_install.sh
  - pip install tox
  - if [[ "${DOCS}" == "true" ]]; then  pip install zip-files; fi
  - pip freeze
  - printenv
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
script:
  # any failure stops testing immediately
  - set -e
  - |
    if [[ "${DOCS}" == "true" ]]; then
      source .travis/doctr_build.sh
    else
      tox -e $TOXENV
    fi
  - echo "DONE"
after_success:
  # coveralls is prone to random failures (which would fail the Travis job), so we'll handle those silently
  - if [[ "${TOXENV}" =~ test ]]; then tox -e $(echo "${TOXENV}" | sed s/test/runcmd/) -- coveralls -v || echo "Cannot upload to coveralls"; fi
notifications:
  webhooks: https://coveralls.io/webhook
