name: binder
channels:
  - conda-forge
dependencies:
  - python=3.8
  - qutip
  - matplotlib
  - pip:
    - watermark
    - symbolic_equation>=0.3.0
    - git+https://github.com/qalgebra/qalgebra.git@master#egg=qalgebra
